name: teno_datetime
description: Extensions for DateTime for convenience
version: 1.0.0
repository: https://github.com/hnvcam/teno_datetime

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  intl: ^0.18.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.9
