name: teno_datetime
description: Extensions for DateTime for a more convenient way of using it. Inspired by Jiffy and MonentJS but no introducing new data type.
version: 1.0.8
repository: https://github.com/hnvcam/teno_datetime

environment:
  sdk: ^3.1.5

# Add regular dependencies here.
dependencies:
  intl: any

dev_dependencies:
  intl_translation: any
  lints: ^5.0.0
  test: ^1.24.9
