name: teno_datetime
description: Extensions for DateTime for a more convenient way of using it. Inspired by Jiffy and MonentJS but no introducing new data type.
version: 1.1.0
repository: https://github.com/hnvcam/teno_datetime

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  intl: ^0.20.2

dev_dependencies:
  intl_translation: ^0.20.0
  lints: ^5.0.0
  test: ^1.25.0
